### ISSUE TITLE
nodejs clustering causes high cpu infinite loop when TCPIP stack interrupted

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [ibmruntimes/node-zos#20]
## Summary
When nodejs has an HTTP(S) server running, and the TCPIP stack on z/OS is interrupted, nodejs will try to read from the listening socket and receive an error. Without clustering, this error is uncaught by default and it throws an exception that stops the program. This is OK. But when using clustering, the error is not received by the JS code, and the program will rapidly re-read the socket over and over, causing very high CPU usage until stopped by the operator.

* **Version**: v12, v14, v16
* **Platform**: z/os
* **Subsystem**: net, http, or cluster

### What steps will reproduce the bug?

Create a nodejs cluster that binds to a TCP port and listens for http connections.
This can be as simple as the example from nodejs' own documentation: https://nodejs.org/docs/latest-v14.x/api/cluster.html
```javascript
const cluster = require('cluster');
const http = require('http');
const numCPUs = require('os').cpus().length;

if (cluster.isMaster) {
  console.log(`Master ${process.pid} is running`);

  // Fork workers.
  for (let i = 0; i < numCPUs; i++) {
    cluster.fork();
  }

  cluster.on('exit', (worker, code, signal) => {
    console.log(`worker ${worker.process.pid} died`);
  });
} else {
  // Workers can share any TCP connection
  // In this case it is an HTTP server
  http.createServer((req, res) => {
    res.writeHead(200);
    res.end('hello world\n');
  }).listen(8000);

  console.log(`Worker ${process.pid} started`);
}
```

We can trigger the bug in the summary above but also in DVIPA, which will cause the -3448 error below.

### How often does it reproduce? Is there a required condition?
Every single time.

### What is the expected behavior?
To instead throw an exception which could either be handled or shut down the server without looping.
When not using cluster mode, this exception is thrown:

```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: accept Unknown system error -3448
    at TCP.onconnection (net.js:1544:24)
Emitted 'error' event on Server instance at:
    at TCP.onconnection (net.js:1544:10) {
  errno: -3448,
  code: 'Unknown system error -3448',
  syscall: 'accept'
}
```

### What do you see instead?
Node will consume high CPU, forever. It might be a single CPU core that's effected, but it's certainly high.

**Comment by IgorTodorovskiIBM** [comment]
Hi @1000TurquoisePogs , do you have more details on how you were able to get the TCPIP stack on z/OS to be interrupted, so that we can reproduce the issue.

**Comment by IgorTodorovskiIBM** [comment]
It if it's easier to show us via a webex or zoom call, please let us know.

**Comment by 1000TurquoisePogs** [comment]
Hi Igor. We can reproduce this in 2 environments, one with dvipa and I think the other is without.

For the simple case, the TCP/IP address space (process) was terminated (by an operator/systems programmer) and restarted in order to resolve an issue, and this triggered the problem. When the node code is listening, the following MVS console commands were issued by an operator:

    P TCPIP
    (Wait 15 seconds)
    S TCPIP

When you get the issue, you'll see the CPU usage go up significantly.

**Comment by PeterFandelAtRocket** [comment]
Hi Igor, have you been able to reproduce the problem?

**Comment by IgorTodorovskiIBM** [comment]
Hi, I was able to reproduce it with this script (leveraging zoau):
```
node cluster.js > output.stdout 2> output.stderr &
sleep 10
opercmd "P TCPIP"
sleep 15
opercmd "S TCPIP"
```

In the nocluster case though, I see a different exception:
```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: accept EIO
    at TCP.onconnection (node:net:1561:24)
Emitted 'error' event on Server instance at:
    at TCP.onconnection (node:net:1561:10) {
  errno: -122,
  code: 'EIO',
  syscall: 'accept'
}
```
We'll investigate the Node.js code for potential causes

**Comment by gabylb** [comment]
Hi @1000TurquoisePogs, we have resolved this issue and will release the fix in the upcoming PTF (1Q 2023).

**Comment by 1000TurquoisePogs** [comment]
That's great news. Will that be a specific revision of node? (14, 16, 18?)

**Comment by gabylb** [comment]
The fix will be in v14 and v16. In our tests of v18, the processes already terminate when TCPIP is interrupted.

**Comment by armstro** [comment]
Any update on PTF for V14 and V16? I would like to document as recommended level with PTF number

**Comment by gabylb** [comment]
The next PTF for V14 will be PTF 12, and for V16 it will be PTF 5.

**Comment by armstro** [comment]
Can this issue be closed?

**Comment by gabylb** [comment]
Issue has been fixed in Node.js v14.21.3 and v16.19.1. Please reopen if you still encounter the issue.
