### ISSUE TITLE
node 18.12.1 crashes with rc=137 on repeat https requests

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [ibmruntimes/node-zos#21]
We're testing zowe to prepare it for node v18 compatibility.
At first, many tests pass, but eventually zowe crashes with rc=137.
We've tried to isolate the cause, and narrowed it down to the absence/presence of a periodic https request.
Sometimes zowe will crash in 30 minutes, sometimes in 1 hour, I'm not sure what causes the differences, but eventually 18 will crash.

* **Version**: v18.12.1
* **Platform**: z/OS 2.4
* **Subsystem**: https, maybe?

### What steps will reproduce the bug?
I can reproduce this with a simple test case:

```
const https = require('https');

const { version } = require('node:process');

console.log(`NodeJS test with Version: ${version}`);

const interval = 30 * 1000;

const startTime = new Date().getTime();

const options = {
  hostname: 'encrypted.google.com',
  port: 443,
  path: '/',
  method: 'GET',
};

setInterval(() => {
  const now = new Date().getTime();
  let elapsed = now - startTime;
  let secs = elapsed / 1000;
  elapsed = Math.floor(elapsed % 1000);

  let minutes = secs / 60;
  secs = Math.floor(secs % 60);

  let hours = minutes / 60;
  minutes = Math.floor(minutes % 60);
  hours = Math.floor(hours % 24);

  const elapsedTime = hours + "h " + minutes + "m " + secs + "." + elapsed + "s";
  console.log(`Request at: ${elapsedTime}`);

  const req = https.request(options, (res) => {
   console.log('statusCode: ', res.statusCode);
   res.on('data', (d) => {
     console.log('data len: '+d.length);
   });
  });

  req.on('error', (e) => {
   console.error(e);
  });
  req.end();
}, interval);
```

30 seconds between requests is what zowe's doing, maybe this can be triggered with a shorter interval to make it easier to diagnose. I'll update if I see that.

Anyway, when running this, it crashes and I see rc=137 when i `echo $?` as seen in 
![image](https://user-images.githubusercontent.com/30730276/221219365-f5a36aab-020d-40d1-aaf1-aa0d656ec823.png)

### How often does it reproduce? Is there a required condition?
It eventually happens, without fail, but how long it takes to happen seems to vary a little.

### Additional information

I don't see an associated ABEND or CEEDUMP so I don't know what's actually wrong.

**Comment by 1000TurquoisePogs** [comment]
I reduced the interval to 10 seconds and yet saw no difference in crash time - still crashed at the 1 hour mark for me despite more frequent requests.
meanwhile i've been running the same test code on node 16 and it's been running for hours no problem.
![image](https://user-images.githubusercontent.com/30730276/221235263-59129e69-8a11-4f58-aad5-76dff8deed5b.png)

**Comment by 1000TurquoisePogs** [comment]
Some searching I did suggested rc=137 could be -9 / SIGKILL, but i'm not issuing any kill and when I was looking at memory, as best as I could tell it's not running out of memory.

**Comment by gabylb** [comment]
Thanks for reporting the issue and providing a test to reproduce. We'll investigate it.

**Comment by 1000TurquoisePogs** [comment]
Thank you. Just a little update: I tried to monitor this up to the point of crash and saw no cpu or memory difference between node 16 and 18 with the tools I used. They both were around 260mb & 0% cpu.

**Comment by gabylb** [comment]
We have a potential fix for this issue and are currently testing it.

**Comment by janiago** [comment]
Similar issue here. My application also abends each hour. 

And I have noticed wrong output into log file. 
below is the normal pattern of log, similar log output each 5 minute.

> Fri, 10 Mar 2023 03:55:00 GMT------------ sampleRotate onTick start
> Fri, 10 Mar 2023 03:55:00 GMT>>>>>>>>>>>> updateConnSampleData start
> Fri, 10 Mar 2023 03:55:00 GMT>>>>>>>>>>>> updateConnSampleTemp start
> 1
> 2
> 3
> 4
> 5
> Fri, 10 Mar 2023 03:55:00 GMT>>>>>>>>>>>> updateConnSampleTemp end
> Fri, 10 Mar 2023 03:55:00 GMT>>>>>>>>>>>> updateLocalStat start
> Fri, 10 Mar 2023 03:55:00 GMT>>>>>>>>>>>> updateLocalStat end
> Fri, 10 Mar 2023 03:55:00 GMT>>>>>>>>>>>> updateConnSampleData end
> Fri, 10 Mar 2023 03:55:00 GMT------------ sampleRotate onTick end

But sometimes it outputs as below: 

> Fri, 10 Mar 2023 04:10:00 GMT------------ sampleRotate onTick start
> Fri, 10 Mar 2023 04:10:00 GMT>>>>>>>>>>>> updateConnSampleData start
> Fri, 10 Mar 2023 04:10:00 GMT>>>>>>>>>>>> updateConnSampleTemp start
> Fri, 10 Mar 2023 **_04:05:00_** GMT>>>>>>>>>>>> updateConnSampleTemp end
> Fri, 10 Mar 2023 **_04:05:00_** GMT>>>>>>>>>>>> updateLocalStat start
> Fri, 10 Mar 2023 **_04:05:00_** GMT>>>>>>>>>>>> updateLocalStat end
> Fri, 10 Mar 2023 **_04:05:00_** GMT>>>>>>>>>>>> updateConnSampleData end
> Fri, 10 Mar 2023 **_04:05:00_** GMT------------ sampleRotate onTick end
> Fri, 10 Mar 2023 04:10:00 GMT>>>>>>>>>>>> updateConnSampleTemp end
> Fri, 10 Mar 2023 04:10:00 GMT>>>>>>>>>>>> updateLocalStat start
> Fri, 10 Mar 2023 04:10:00 GMT>>>>>>>>>>>> updateLocalStat end
> Fri, 10 Mar 2023 04:10:00 GMT>>>>>>>>>>>> updateConnSampleData end
> Fri, 10 Mar 2023 04:10:00 GMT------------ sampleRotate onTick end

Please see the highlighted time above. Those lines should be 12345, but they are replaced with some other content that was already output at earlier time. 
The time is simply output of "(new Date()).toUTCString()", and "04:05:00" should not print after "04:10:00"

I'm not sure it's similar issue related to stream? 

Thanks!

**Comment by gabylb** [comment]
Hi @janiago, do you have a reduced .js that can reproduce the issue (backward time displayed instead of the 12345 lines)? About time going backwards, I ran the following test and the time was displayed correctly for the 30 minutes that it ran:
```
const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));
const interval = 1000;
const reps = 1800;
var dt;

async function main() {
  for (var i=0; i<reps; i++) {
    dt = (new Date()).toUTCString();
    console.log(dt);
    await sleep(interval);
  }
}
main();
```

**Comment by janiago** [comment]
> 
Hi @gabylb, I'm trying to reproduce the issue with simpler code. Will update once I get any conclusion.
Thanks.

**Comment by janiago** [comment]
> 

Hi @gabylb, I'm trying to reproduce the issue with simpler code. Will update once I get any conclusion.
Thanks.

**Comment by janiago** [comment]
Hi @gabylb , 
I was trying to narrow down the code that cause the abend, and got something different from https requests. Could you test whether your fix also works for below code? It abends at iteration 65 in my testing ENV. 

```
/**
 * Need npm i better-queue to run it.
 */
const Queue = require('better-queue')
/**
 * The function to invoke for each item in queue.
 * @param {*} iterationNo A number received
 * @param {*} callback Function to invoke when the item in queue is processed.
 */
function processItemInQueue(iterationNo, callback) {
    // Do nothing but invoke callback function
    callback({message: 'Do testing for iteration ' + iterationNo})
}
const testQueue = new Queue(processItemInQueue, { maxRetries: 0})

let iteNo = 0 // Iteration number
setInterval(async () => {
    console.log((new Date()).toUTCString() + ' >>> Iteration ' + (++ iteNo))
    testQueue.push(iteNo, (msgObj) => { // Push the iteration number into queue, and it will invoke the callback
        console.log((new Date()).toUTCString() + ' > Message from queue: ' + msgObj.message)
    })
}, 60000)
```
Here is what I get in putty: 
![image](https://user-images.githubusercontent.com/40502604/224926657-332fbc07-ec06-4868-8d51-cfa1f7a311fb.png)

![image](https://user-images.githubusercontent.com/40502604/224926433-1a7a090f-962c-446b-adca-e207a0bba57e.png)


Regarding the log issue, I have reviewed the log file, and the issue doesn't exist. I guess it was putty's display error while I was tracking the log with "tail -f xxx.log" and re-sized putty window for several times...
Sorry for the misleading message.

Thanks!

**Comment by gabylb** [comment]
> Hi @gabylb , I was trying to narrow down the code that cause the abend, and got something different from https requests. Could you test whether your fix also works for below code? It abends at iteration 65 in my testing ENV.
> 

@janiago your test ran fine with our fix, for some 18 hours, then I terminated it:
```
Tue, 14 Mar 2023 20:48:21 GMT >>> Iteration 1
Tue, 14 Mar 2023 20:48:21 GMT > Message from queue: Do testing for iteration 1
Tue, 14 Mar 2023 20:49:21 GMT >>> Iteration 2
Tue, 14 Mar 2023 20:49:21 GMT > Message from queue: Do testing for iteration 2
...
Wed, 15 Mar 2023 15:00:22 GMT >>> Iteration 1093
Wed, 15 Mar 2023 15:00:22 GMT > Message from queue: Do testing for iteration 1093
```

**Comment by janiago** [comment]
> 

Thank you very much @gabylb !!!
When will the new version be available?

**Comment by gabylb** [comment]
@janiago we are targeting to release v18 PTF-1 end of March.

**Comment by 1000TurquoisePogs** [comment]
Hi all, I found node 18.14 on the website, and am re-running my test. 24 hours and it's still working, so it seems like node 18 is fixed for me, and we can work on verifying the rest of zowe. thank you!
